# Generated by Django 4.0.4 on 2022-05-23 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=500)),
                ('event_location', models.CharField(max_length=500)),
                ('inventory_needed', models.CharField(max_length=500)),
                ('shipment_date', models.DateField()),
                ('return_date', models.DateField()),
                ('status', models.CharField(max_length=500)),
            ],
        ),
    ]
