# Generated by Django 4.0.4 on 2022-05-23 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='products',
            new_name='events',
        ),
    ]
