# Generated by Django 4.0.4 on 2022-05-23 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('events', '0003_events_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='inventory_needed',
        ),
        migrations.CreateModel(
            name='event_products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=500)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.events')),
                ('event_products', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.products')),
            ],
        ),
    ]
