# Generated by Django 4.0.4 on 2022-05-24 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_events_inventory_needed_event_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='user',
        ),
    ]
