# Generated by Django 3.2.13 on 2022-05-25 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_events_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='google_event_id',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
