# Generated by Django 3.2.13 on 2022-05-19 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_products_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='quantity',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
