# Generated by Django 3.2.13 on 2022-05-19 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_products_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='products',
        ),
    ]
