# Generated by Django 4.0.4 on 2022-05-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='quantity_in_use',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
