# Generated by Django 4.0.4 on 2022-05-23 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_quantity_in_use'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='quantity_in_use',
            new_name='quantity_left',
        ),
    ]
