# Generated by Django 4.0.4 on 2022-05-24 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_quantity_in_use_products_quantity_left'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='user',
        ),
    ]
